name: Api-Infrastructure

on:
  push:
    branches:
      - feature/fn-bicep
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Azure Login
      uses: Azure/login@v2.2.0            
      with:
        client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
        tenant-id: ${{ secrets.AZURE_Tenant_ID }}
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
    - uses: Azure/arm-deploy@v2
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: AutomatedInfra
        template: ./Infrastructure/api.bicep
        parameters: environmentType=${{ env.ENVIRONMENT }}
