name: Provision and Deploy

on:
  push:
    branches:
      - main
      - feature/my-diversion-then-ai-bringing-back-in

permissions:
  id-token: write
  contents: read

env:  
  DEPLOYMENT_RESOURCEGROUP_NAME: AutomatedInfra
  DATABASE_RESOURCEGROUP_NAME: ${{ secrets.DATABASE_RESOURCEGROUP_NAME }}
  MANAGEMENT_RESOURCEGROUP_NAME: ${{ secrets.MANAGEMENT_RESOURCEGROUP_NAME }}
  AZURE_KEYVAULT_NAME: ${{ secrets.AZURE_KEYVAULT_NAME }}
  storageName: cultpodcastsstg
  suffix: infra
  location: uksouth
  functionState: start
  COSMOS_DEPLOYMENT_NAME: infra-cosmos
  API_PACKAGE_PATH: './Cloud/Api' 
  DISCOVER_PACKAGE_PATH: './Cloud/Discovery' 
  INDEXER_PACKAGE_PATH: './Cloud/Indexer' 
  DOTNET_VERSION: '9.0.x' 
  buildConfiguration: 'Release'
  TARGET_RUNTIME: 'linux-x64'
  outputApi: 'output/api'
  outputDiscover: 'output/discover'
  outputIndexer: 'output/indexer'
  artifactApi: 'api'
  artifactDiscover: 'discover'
  artifactIndexer: 'indexer'
  artifactInfrastructure: 'infrastructure'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      infrastructure_changed: ${{ steps.changes.outputs.infrastructure }}
    strategy:
      matrix:
        project:
          - name: api
            path: './Cloud/Api'
            output: 'output/api'
            artifact: 'api'
          - name: discover
            path: './Cloud/Discovery'
            output: 'output/discover'
            artifact: 'discover'
          - name: indexer
            path: './Cloud/Indexer'
            output: 'output/indexer'
            artifact: 'indexer'
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          infrastructure:
          - ./Infrastructure/**
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore /p:Configuration=Release -r ${{ env.TARGET_RUNTIME }}
    - name: Publish ${{ matrix.project.name }}
      run: dotnet publish --configuration ${{ env.buildConfiguration }} -r ${{ env.TARGET_RUNTIME }} ${{ matrix.project.path }} -o:${{ matrix.project.output }}
    - name: Archive ${{ matrix.project.name }} artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project.artifact }}
        path: ${{ matrix.project.output }}
        include-hidden-files: true

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test --configuration ${{ env.buildConfiguration }} --no-restore --verbosity normal

  archive-infrastructure:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          infrastructure:
          - ./Infrastructure/**
    - name: Archive bicep artifacts
      if: steps.changes.outputs.infrastructure == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifactInfrastructure }}
        path: Infrastructure
        include-hidden-files: true

  provision:
    runs-on: ubuntu-latest
    needs: [build, test, archive-infrastructure]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/my-diversion-then-ai-bringing-back-in'
    continue-on-error: false
    steps:
    - name: Download bicep artifact
      uses: actions/download-artifact@v4
      if: needs.build.outputs.infrastructure_changed == 'true'
      with:
          name: ${{ env.artifactInfrastructure }}
          path: Infrastructure
    - name: Display structure of downloaded files
      run: ls -R -a .
      if: needs.build.outputs.infrastructure_changed == 'true'
    
    - name: Azure Login
      uses: Azure/login@v2.2.0            
      if: needs.build.outputs.infrastructure_changed == 'true'
      with:
        client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
        tenant-id: ${{ secrets.AZURE_Tenant_ID }}
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}

    - name: Cosmos DB (Deploy Bicep)
      id: bicepcosmosdeploy
      uses: azure/bicep-deploy@v1
      if: needs.build.outputs.infrastructure_changed == 'true'
      with:
        type: deployment
        operation: create
        name: ${{ env.COSMOS_DEPLOYMENT_NAME }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DATABASE_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/cosmos-db.bicep
        parameters: '{"location":"${{ env.location }}", "cosmosAccountName":"${{ secrets.COSMOS_ACCOUNT_NAME }}"}'
    - name: Storage (Deploy Bicep)
      id: bicepstoragedeploy
      uses: azure/bicep-deploy@v1
      if: needs.build.outputs.infrastructure_changed == 'true'
      with:
        type: deployment
        operation: create
        name: bicep-storage-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/function-storage.bicep
        parameters: '{"location":"${{ env.location }}", "storageName":"${{ env.storageName }}"}'
    - name: Application-Insights (Deploy Bicep)
      id: bicepappinsightsdeploy
      uses: azure/bicep-deploy@v1
      if: needs.build.outputs.infrastructure_changed == 'true'
      with:
        type: deployment
        operation: create
        name: bicep-appinsights-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/function-application-insights.bicep
        parameters: '{"location":"${{ env.location }}", "suffix":"${{ env.suffix }}"}'
    - name: Functions (Deploy Bicep)
      id: bicepfunctionsdeploy
      uses: azure/bicep-deploy@v1
      if: needs.build.outputs.infrastructure_changed == 'true'
      with:
        type: deployment
        operation: create
        name: bicep-functions-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/functions.bicep
        parameters-file: ./Infrastructure/functions.bicepparam
        parameters: '{"location":"${{ env.location }}", "suffix":"${{ env.suffix }}", "storageName":"${{ env.storageName }}"}'

    - name: Set Function State
      if: ${{ ((env.functionState == 'start') || (env.functionState == 'stop')) && needs.build.outputs.infrastructure_changed == 'true' }}
      uses: Azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          az functionapp ${{ env.functionState }} --name api-${{ env.suffix }} --resource-group ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
          az functionapp ${{ env.functionState }} --name indexer-${{ env.suffix }} --resource-group ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
          az functionapp ${{ env.functionState }} --name discover-${{ env.suffix }} --resource-group ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}

  api-deploy:
    runs-on: ubuntu-latest
    needs: provision
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/my-diversion-then-ai-bringing-back-in'
    permissions:
      id-token: write #This is required for requesting the JWT
    continue-on-error: false
    steps:
      - name: Download api artifact
        uses: actions/download-artifact@v4
        with:
            name: ${{ env.artifactApi }}
            path: ${{ env.outputApi }}
      - name: Display structure of downloaded files
        run: ls -R -a .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
          tenant-id: ${{ secrets.AZURE_Tenant_ID }}
          subscription-id: ${{ secrets.AZURE_Subscription_ID }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'api-infra'
          slot-name: 'Production'
          package: ${{ env.outputApi }}

  discover-deploy:
    runs-on: ubuntu-latest
    needs: provision
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/my-diversion-then-ai-bringing-back-in'
    permissions:
      id-token: write #This is required for requesting the JWT
    continue-on-error: false
    steps:
      - name: Download api artifact
        uses: actions/download-artifact@v4
        with:
            name: ${{ env.artifactDiscover }}
            path: ${{ env.outputDiscover }}
      - name: Display structure of downloaded files
        run: ls -R -a .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
          tenant-id: ${{ secrets.AZURE_Tenant_ID }}
          subscription-id: ${{ secrets.AZURE_Subscription_ID }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'discover-infra'
          slot-name: 'Production'
          package: ${{ env.outputDiscover }}

  indexer-deploy:
    runs-on: ubuntu-latest
    needs: provision
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/my-diversion-then-ai-bringing-back-in'
    permissions:
      id-token: write #This is required for requesting the JWT
    continue-on-error: false
    steps:
      - name: Download api artifact
        uses: actions/download-artifact@v4
        with:
            name: ${{ env.artifactIndexer }}
            path: ${{ env.outputIndexer }}
      - name: Display structure of downloaded files
        run: ls -R -a .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
          tenant-id: ${{ secrets.AZURE_Tenant_ID }}
          subscription-id: ${{ secrets.AZURE_Subscription_ID }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'indexer-infra'
          slot-name: 'Production'
          package: ${{ env.outputIndexer }}

