name: Api-Infrastructure

on:
  push:
    branches:
      - feature/fn-bicep
  workflow_dispatch:

env:
    DEPLOYMENT_RESOURCEGROUP_NAME: AutomatedInfra
    MANAGEMENT_RESOURCEGROUP_NAME: ${{ secrets.MANAGEMENT_RESOURCEGROUP_NAME }}
    AZURE_KEYVAULT_NAME: ${{ secrets.AZURE_KEYVAULT_NAME }}
    storageName: cultpodcastsstg
    suffix: infra
    location: uksouth

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v4
    - name: Azure Login
      uses: Azure/login@v2.2.0            
      with:
        client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
        tenant-id: ${{ secrets.AZURE_Tenant_ID }}
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
    - name: Storage (Validate Bicep)
      id: bicepstoragevalidate
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: validate
        name: bicep-validate-storage-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/function-storage.bicep
        parameters: '{"location":"${{ env.location }}", "storageName":"${{ env.storageName }}"}'
    - name: Storage (Deploy Bicep)
      id: bicepstoragedeploy
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: create
        name: bicep-storage-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/function-storage.bicep
        parameters: '{"location":"${{ env.location }}", "storageName":"${{ env.storageName }}"}'



    - name: Application-Insights (Validate Bicep)
      id: bicepappinsightsvalidate
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: validate
        name: bicep-validate-appinsights-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/function-application-insights.bicep
        parameters: '{"location":"${{ env.location }}", "suffix":"${{ env.suffix }}"}'
    - name: Application-Insights (Deploy Bicep)
      id: bicepappinsightsdeploy
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: create
        name: bicep-appinsights-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/function-application-insights.bicep
        parameters: '{"location":"${{ env.location }}", "suffix":"${{ env.suffix }}"}'


    - name: Main (Validate Bicep)
      id: bicepmainvalidate
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: validate
        name: bicep-validate-main-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/main.bicep
        parameters-file: ./Infrastructure/main.bicepparam
        parameters: '{"location":"${{ env.location }}", "suffix":"${{ env.suffix }}", "storageName":"${{ env.storageName }}"}'
    - name: Main (Deploy Bicep)
      id: bicepmaindeploy
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: create
        name: bicep-main-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/main.bicep
        parameters-file: ./Infrastructure/main.bicepparam
        parameters: '{"location":"${{ env.location }}", "suffix":"${{ env.suffix }}", "storageName":"${{ env.storageName }}"}'
