name: Api-Infrastructure

on:
  push:
    branches:
      - feature/fn-bicep
  workflow_dispatch:

env:
    DEPLOYMENT_RESOURCEGROUP_NAME: AutomatedInfra
    LOCATION: uksouth

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Print Resource Group
      run: echo "Resource-group $DEPLOYMENT_RESOURCEGROUP_NAME"
    - name: Azure Login
      uses: Azure/login@v2.2.0            
      with:
        client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
        tenant-id: ${{ secrets.AZURE_Tenant_ID }}
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
    - name: Storage
      uses: Azure/arm-deploy@v2
      with:
        deploymentName: storage-${{ github.run_number }}
        resourceGroupName: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template: ./Infrastructure/function-storage.bicep
        parameters: 'location=${{ env.LOCATION }}'