name: Api-Infrastructure

on:
  push:
    branches:
      - feature/fn-bicep
  workflow_dispatch:

env:
    DEPLOYMENT_RESOURCEGROUP_NAME: AutomatedInfra
    MANAGEMENT_RESOURCEGROUP_NAME: ${{ secrets.MANAGEMENT_RESOURCEGROUP_NAME }}
    AZURE_KEYVAULT_NAME: ${{ secrets.AZURE_KEYVAULT_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v4
    - name: Azure Login
      uses: Azure/login@v2.2.0            
      with:
        client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
        tenant-id: ${{ secrets.AZURE_Tenant_ID }}
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
    - name: Bicep Storage (Validate)
      id: bicepstoragevalidate
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: validate
        name: bicep-validate-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/function-storage.bicep
        parameters: '{"location":"uksouth", "storageName":"cultpodcastsstg"}'
    - name: Bicep Storage (Deploy)
      id: bicepstoragedeploy
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: create
        name: bicep-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/function-storage.bicep
        parameters: '{"location":"uksouth", "storageName":"cultpodcastsstg"}'
    - name: Bicep Main (Validate)
      id: bicepmainvalidate
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: validate
        name: bicep-validate-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/main.bicep
        parameters-file: ./Infrastructure/main.bicepparam
    - name: Bicep Main (Deploy)
      id: bicepmaindeploy
      uses: azure/bicep-deploy@v1
      with:
        type: deployment
        operation: create
        name: bicep-${{ github.run_number }}
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
        resource-group-name: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template-file: ./Infrastructure/main.bicep
        parameters-file: ./Infrastructure/main.bicepparam
