name: Api-Infrastructure

on:
  push:
    branches:
      - feature/fn-bicep
  workflow_dispatch:

env:
    DEPLOYMENT_RESOURCEGROUP_NAME: AutomatedInfra
    LOCATION: uksouth

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Azure Login
      uses: Azure/login@v2.2.0            
      with:
        client-id: ${{ secrets.DEPLOYMENT_Client_ID }}
        tenant-id: ${{ secrets.AZURE_Tenant_ID }}
        subscription-id: ${{ secrets.AZURE_Subscription_ID }}
    - name: Storage
      id: storage
      uses: Azure/arm-deploy@v2
      with:
        deploymentName: storage-${{ github.run_number }}
        resourceGroupName: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template: ./Infrastructure/function-storage.bicep
        parameters: 'location=${{ env.LOCATION }}'
    - name: Application Insights
      id: applicationInsights
      uses: Azure/arm-deploy@v2
      with:
        deploymentName: ai-${{ github.run_number }}
        resourceGroupName: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template: ./Infrastructure/function-application-insights.bicep
        parameters: 'location=${{ env.LOCATION }}'
    - name: Function 1
      uses: Azure/arm-deploy@v2
      with:
        deploymentName: fn1-${{ github.run_number }}
        resourceGroupName: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template: ./Infrastructure/function.bicep
        parameters: 'location=${{ env.LOCATION }} name=Function1 runtime=dotnet storageAccountName=steps.storage.outputs.storageAccountName storageAccountId=steps.storage.outputs.storageAccountId instrumentationKey=steps.applicationInsights.outputs.instrumentationKey'
    - name: Function 2
      uses: Azure/arm-deploy@v2
      with:
        deploymentName: fn2-${{ github.run_number }}
        resourceGroupName: ${{ env.DEPLOYMENT_RESOURCEGROUP_NAME }}
        template: ./Infrastructure/function.bicep
        parameters: 'location=${{ env.LOCATION }} name=Function1 runtime=dotnet storageAccountName=steps.storage.outputs.storageAccountName storageAccountId=steps.storage.outputs.storageAccountId instrumentationKey=steps.applicationInsights.outputs.instrumentationKey'
